INSERT INTO tbl_hello_world (id,lang,hw_translation) VALUES (1, 'Serbian', 'Zdravo svete');
INSERT INTO tbl_hello_world (id,lang,hw_translation) VALUES (2, 'English', 'Hello world');
INSERT INTO tbl_hello_world (id,lang,hw_translation) VALUES (3, 'Portuguese', 'Olá Mundo');
INSERT INTO tbl_hello_world (id,lang,hw_translation) VALUES (4, 'Swedish', 'Hej världen');
INSERT INTO tbl_hello_world (id,lang,hw_translation) VALUES (5, 'French', 'Bonjour le monde');
INSERT INTO tbl_hello_world (id,lang,hw_translation) VALUES (6, 'German', 'Hallo Welt');
INSERT INTO tbl_hello_world (id,lang,hw_translation) VALUES (7, 'Irish', 'Dia duit Domhanda');
INSERT INTO tbl_hello_world (id,lang,hw_translation) VALUES (8, 'Slovenian', 'Pozdravljen, svet');
INSERT INTO tbl_hello_world (id,lang,hw_translation) VALUES (9, 'Czech', 'Ahoj světe');
INSERT INTO tbl_hello_world (id,lang,hw_translation) VALUES (10, 'Hawaiian', 'Aloha Honua');