DROP TABLE IF EXISTS tbl_hello_world;
DROP TABLE IF EXISTS tbl_users;

CREATE TABLE tbl_hello_world (
id INT AUTO_INCREMENT PRIMARY KEY,
lang VARCHAR(250) NOT NULL,
hw_translation VARCHAR(250) NOT NULL
);

CREATE TABLE tbl_users (
id INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(250) NOT NULL,
password VARCHAR(250) NOT NULL
);